### ISSUE TITLE
Should subprocess.run use the env variable instead of setting the os.environ?

### ISSUE THREAD

**Issue by gadfort** [siliconcompiler/siliconcompiler#1080]
When setting an environmental variable for a program, SC appears to use `os.environ` instead of creating a copy of the current environment and passing that to the subprocess via `, env={}` (https://docs.python.org/3/library/subprocess.html)
https://github.com/siliconcompiler/siliconcompiler/blob/9adcaa7b7780c57e8086a54f026ff08f0e5e9ced/siliconcompiler/core.py#L3839

Using the `os.environ` means the variables are preserved through the subsequent runs which may result in the incorrect behavior? The other option would be to restore the tool environmental variable after the run to prevent leakage. Or is there another mechanism SC uses to address this?

**Comment by nmoroze** [comment]
Good question! Each task currently runs in its own process forked from the parent process (managed by the `multiprocessing` module). Since these tasks run in their own process, any global changes to the environment variables are invisible to the other tasks, and they are not propagated back to the main thread.

Here's a quick program to verify this:
```python
import os
import multiprocessing

def _runtask(i):
    os.environ['MY_INDEX'] = i
    print(f'MY_INDEX thread {i}:', os.environ['MY_INDEX'])

def run():
    procs = []
    for i in range(4):
        p = multiprocessing.Process(target=_runtask, args=(str(i)))
        p.start()
        procs.append(p)

    for p in procs:
        p.join()

    print('MY_INDEX main thread:', os.environ.get('MY_INDEX', '<none>'))

if __name__ == '__main__':
    run()
```

However, this is a good point in that I think setting `os.environ` directly is a bit of a code smell, and it's not very bug-safe, since `_runtask()` is relying on certain assumptions about how it is called to ensure that this is okay. I think it would be reasonable to refactor the code to feed in an environment directly, and I think we can keep this issue open until that's done.
